[package]
name = "acm-present"
version = "0.1.0"
authors = ["Jeffrey McAteer <jeffrey.p.mcateer@gmail.com>"]

[dependencies]
lazy_static = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"
tiny_http = "*"

